"""add change table

Revision ID: 0c83b17b732d
Revises: 1ea321fde006
Create Date: 2023-02-15 19:21:12.462752+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0c83b17b732d"
down_revision = "1ea321fde006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "change",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("incarnation_id", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("requested_version_hash", sa.String(), nullable=False),
        sa.Column("requested_version", sa.String(), nullable=False),
        sa.Column("requested_data", sa.String(), nullable=False),
        sa.Column("commit_sha", sa.String(), nullable=False),
        sa.Column("commit_pushed", sa.Boolean(), nullable=False),
        sa.Column("merge_request_id", sa.String(), nullable=True),
        sa.Column("merge_request_branch_name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["incarnation_id"], ["incarnation.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("incarnation_id", "revision", name="change_incarnation_revision"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("change")
    # ### end Alembic commands ###
